console.log("pasos para cocinar una torta");
console.log("paso 1: buscar los recursos materiales");
console.log("paso 2:obtener una receta de la preparacion");
console.log("paso 3:segir los pasos de la receta");
console.log("pasos para ir al supermercado");
console.log("paso 1: buscar las llaves del auto");
console.log("paso 2:activar el gps del celular");
console.log("paso 3:dirigirse al auto");
console.log("paso 4:dar arranque al auto");
console.log("paso 5: indicar en el gps el destino");
console.log("paso 1: seguir las indicaciones del GPS");
console.log("paso 2:activar el gps del celular");
console.log("paso 3:dirigirse al auto");
